version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --logpath /var/log/mongodb/mongod.log
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - chat_app_network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - PORT=${API_GATEWAY_PORT}
    volumes:
      - ./api-gateway/public_key.pem:/app/public_key.pem
    depends_on:
      - user-service
      - chat-service
    networks:
      - chat_app_network
    develop:
      watch:
        - action: rebuild
          path: ./api-gateway

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - TOKEN_EXP_HS=${TOKEN_EXP_HS}
      - MONGO_URI=${MONGO_URI}
      - PORT=${USER_SERVICE_PORT}
    depends_on:
      - mongodb
    networks:
      - chat_app_network
    develop:
      watch:
        - action: rebuild
          path: ./user-service

  chat-service:
    build:
      context: .
      dockerfile: ./chat-service/Dockerfile
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${CHAT_SERVICE_PORT}
      - MEDIA_SERVICE_URL=${MEDIA_SERVICE_URL}
      - AI_ASSISTANT_URL=${AI_ASSISTANT_URL}
    depends_on:
      - mongodb
    networks:
      - chat_app_network
    develop:
      watch:
        - action: rebuild
          path: ./chat-service

  media-service:
    build:
      context: .
      dockerfile: ./media-service/Dockerfile
    ports:
      - "${MEDIA_SERVICE_PORT}:${MEDIA_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${MEDIA_SERVICE_PORT}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
    depends_on:
      - mongodb
    networks:
      - chat_app_network
    develop:
      watch:
        - action: rebuild
          path: ./media-service

  ai-service:
    build:
      context: .
      dockerfile: ./ai-service/Dockerfile
    ports:
      - "${AI_SERVICE_PORT}:${AI_SERVICE_PORT}"
    environment:
      - PORT=${AI_SERVICE_PORT}
      - OLLAMA_NGROK_URL=${OLLAMA_NGROK_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    networks:
      - chat_app_network
    develop:
      watch:
        - action: rebuild
          path: ./ai-service

networks:
  chat_app_network:
    driver: bridge
